version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Asia/Seoul
    volumes:
      - ~/.n8n:/home/node/.n8n
